version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_TCP_PORT= 3306
      - MYSQL_UNIX_PORT=3306
    ports:
      - "3306:3306"

    volumes:
      - ./mariadb_data:/var/lib/mysql
      

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    


